spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761//eureka}
  instance:
    prefer-ip-address: true
    status-page-url-path: https://${eureka.instance.hostname}/intro
    health-check-url: https://${eureka.instance.hostname}/health
    home-page-url: https://${eureka.instance.hostname}/
    hostname: localhost

